// Auto generated by postsbuild.js  do not edit by hand or risk mega fuckup
export const posts = [
  {
    "slug": "redact-is-fucking-dumb",
    "title": "Redact is fucking dumb",
    "dateISO": "2026-09-27",
    "dateDisplay": "September 27, 2026",
    "description": "Issues i have with the redact product",
    "tags": [
      "i dislike the product i have no opinions on whoever works there"
    ],
    "readingTime": 6,
    "hasAudio": false,
    "parent": null
  }
];
